baseURL = 'https://iridescent-scone-12a762.netlify.app/'
languageCode = 'en-us'
title = 'Online Scam Awareness'
theme = 'ananke'
[taxonomies] 
tag = "tags"
author = "authors"
category = "categories" 



