baseURL = 'https://iridescent-scone-12a762.netlify.app/'
languageCode = 'en-us'
title = 'Online Scam Awareness'
theme = 'ananke'
[taxonomies]
category = "categories"
tags = "tags"
author = "authors"
[[menus.main]]
name = 'phishing'
pageRef = '/Phishing-page'
weight = 10
[[menus.main]]
name = 'pharming'
pageRef = '/Pharming-page'
weight = 20
[[menus.main]]
name = 'smish'
pageRef = '/Smish-page'
weight = 30
[[menus.main]]
name = 'spear'
pageRef = '/Spear-page'
weight = 40
[[menus.main]]
name = 'vishing'
pageRef = '/Vishing-page'
weight = 50
[[menus.main]]
name = 'scam report'
pageRef = '/Scam Report-page'
weight = 60
[[menus.main]]
name = 'hotsheet of scams'
pageRef = '/Hotsheet of scams-page'
weight = 70 
tag = "tags"
author = "authors"
category = "categories" 


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Vishing"
    url = "/posts/vishing/"
    weight = 20

  [[menu.main]]
    name = "Phishing"
    url = "/posts/phishing/"
    weight = 30

  [[menu.main]]
    name = "Pharming"
    url = "/posts/pharming/"
    weight = 40

  [[menu.main]]
    name = "Cloning"
    url = "/posts/cloning/"
    weight = 50

  [[menu.main]]
    name = "Smishing"
    url = "/posts/smishing/"
    weight = 60

  [[menu.main]]
    name = "Spearing"
    url = "/posts/spear-phishing/"
    weight = 70

[[menu.main]]
    name = "Email"
    url = "/posts/email/"
    weight = 80

[[menu.main]]
    name = "Financial"
    url = "/posts/financial/"
    weight = 90


[[menu.main]]
    name = "Report"
    url = "/posts/scam-report/"
    weight = 100

[[menu.footer]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.footer]]
  name = "Vishing"
  url = "/posts/vishing/"
  weight = 20

[[menu.footer]]
  name = "Phishing"
  url = "/posts/phishing/"
  weight = 30

[[menu.footer]]
  name = "Pharming"
  url = "/posts/pharming/"
  weight = 40

[[menu.footer]]
  name = "Cloning"
  url = "/posts/cloning/"
  weight = 50

[[menu.footer]]
  name = "Smishing"
  url = "/posts/smishing"
  weight = 60

[[menu.footer]]
  name = "Spearing"
  url = "/posts/spearing"
  weight = 70

[[menu.footer]]
  name = "Email Scams"
  url = "/posts/email"
  weight = 80

[[menu.footer]]
  name = "Financial Scams"
  url = "/posts/financial"
  weight = 90

[[menu.footer]]
  name = "Report a Scam"
  url = "/posts/report"
  weight = 100

[[menu.main]]
  name = "Browse Topics"
  url = "/browse/"
  weight = 110



